import './globals.css'
import type { Metadata } from 'next'
import { Alata } from 'next/font/google'

const alata = Alata({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Frontend Mentor | Loopstudios landing page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={alata.className}>{children}</body>
    </html>
  )
}
